def decodeltr()
    decodeltr = ""
    A=(*-)
    B=(-***)
    C=(-*-*)
    D=(-**)
    E=(*)
    F=(**-*)
    G=(--*)
    H=(***)
    I=(**)
    J=(*---)
    K=(-*-)
    L=(*-**)
    M=(--)
    N=(-*)
    O=(---)
    P=(*--*)
    Q=(--*-)
    R=(*-*)
    S=(***)
    T=(-)
    U=(**-)
    V=(***-)
    W=(*--)
    X=(-**-)
    Y=(-*--)
    Z=(--**)

    one=(*----)
    two=(**---)
    three=(***--)
    four=(****-)
    five=(*****)
    six=(-****)
    seven=(--***)
    eight=(---**)
    nine=(----*)
    zero=(-----)
    
    Period=(*-*-*-)
    Comma=(--**--)
    Colon=(---***)
    Question_Mark=(**--**)
    Apostrophe=(*----*)
    Hyphen=(-****-)
    Fraction_Bar=(-**-*)
    Parentheses=(-*--*-)
    Quotation_Marks=(*-**-*)
    
    return decodeltr
end